apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appFirstName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appFirstName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appFirstName }}
    spec:
      imagePullSecrets: 
        - name: regcgreen
      # imagePullSecrets: {{- range .Values.deployment.image.pullSecrets }}
      # - {{ . }}
      # {{- end}}
      containers:
        - image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          name: {{ .Values.deployment.appFirstName }}
          env:
            - name: TZ
              value: America/Chicago
            - name: PREP_DB_NAME
              value: prep
            - name: PREP_DB_USER
              value: prep
            - name: PREP_DB_HOST
              value: {{ .Values.deployment.appFirstName }}-postgresql
            # - name: PREP_DB_PORT
            #   value: 5432
            - name: PREP_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.appFirstName }}-postgresql
                  key: password
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
