apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appFirstName }}
spec:
  selector:
    app: {{ .Values.deployment.appFirstName }}
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prep
spec:
  parentRefs:
  - name: iamyassin08-gateway
    namespace: istio-ingress
  hostnames: {{- range .Values.deployment.hostnames }}
      - {{ . }}
      {{- end}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.deployment.appFirstName }}
      port: 80
