definitions:
  handler.UserReq:
    properties:
      Email:
        type: string
      FirstName:
        type: string
      LastName:
        type: string
      UserID:
        type: string
    type: object
  handler.UserRes:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get All Users in DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.UserRes'
            type: array
      summary: List Users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create User Params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.UserReq'
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.UserRes'
      security:
      - ApiKeyAuth: []
      summary: Create A User
      tags:
      - User
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User by Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete A User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: get User by Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UserRes'
      security:
      - ApiKeyAuth: []
      summary: Get A User By ID
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Update User by Id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: Update User Params
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/handler.UserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Update A User
      tags:
      - User
swagger: "2.0"
