apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appName }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prep-app
  # namespace:prep-dev
spec:
  parentRefs:
  - name: nuri-gateway
    namespace: istio-ingress
  hostnames: {{- range .Values.deployment.hostnames }}
      - {{ . }}
      {{- end}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.deployment.appName }}
      port: 5173