volumes:
  db:
services:
  backend:
    container_name: prep
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GOOSE_DRIVER=sqlite3                                
      - GOOSE_DBSTRING=./app.db
      - GOOSE_MIGRATION_DIR=./sqlite/migration
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/healthz || exit 1
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 15s
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 128M
    volumes:
      - .:/app
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:8080