name: Docker Image CI
permissions:
  contents: write
on:
  push:
    branches: [ "develop"]
  # pull_request:
  #   branches: [ "develop" ]
jobs:
  build-dev:
    environment: dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 8
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        # load: true
        push: true
        tags: |
          iamyassin/prep-app:dev
          iamyassin/prep-app:latest
          iamyassin/prep-app:snapshot-${{ steps.short-sha.outputs.sha }}
    - name: Tag release
      run: |
        cd infra/dev
        sed -i 's|tag: .*|tag: snapshot-${{ steps.short-sha.outputs.sha }}|' version.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add version.yaml
        git commit -m 'Update versions.yaml to snapshot-${{ steps.short-sha.outputs.sha }}'
        cat version.yaml
        git tag -fa nightly -m 'Tagging Repository with latest deployment snapshot-${{ steps.short-sha.outputs.sha }}' 
        git push --force origin refs/tags/nightly:refs/tags/nightly

    #git push -f origin tag nightly